site: Radis

collections:
  - features
  - goals
  - scenarios
  - users

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-sitemap

# Google Analytics
google_analytics: UA-113616205-2